"""add refresh_interval_days to lead_types

Revision ID: 018fba6ca502
Revises: a2662c8d5973
Create Date: 2026-03-26 11:06:07.021466

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '018fba6ca502'
down_revision: Union[str, None] = 'a2662c8d5973'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lead_types', sa.Column('refresh_interval_days', sa.Integer(), server_default='30', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lead_types', 'refresh_interval_days')
    # ### end Alembic commands ###
