"""initial schema

Revision ID: a2662c8d5973
Revises: 
Create Date: 2026-03-25 21:50:49.778508

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a2662c8d5973'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('geographies',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('geo_type', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('state_code', sa.String(length=2), nullable=False),
    sa.Column('county_name', sa.String(length=255), nullable=True),
    sa.Column('fips_code', sa.String(length=10), nullable=True),
    sa.Column('zillow_slug', sa.String(length=255), nullable=False),
    sa.Column('population', sa.Integer(), nullable=True),
    sa.Column('priority_tier', sa.SmallInteger(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('geo_type', 'name', 'state_code', name='uq_geography')
    )
    op.create_table('lead_types',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('slug', sa.String(length=50), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('url_template', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('pipeline_stages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('slug', sa.String(length=50), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('stage_order', sa.Integer(), nullable=False),
    sa.Column('is_terminal', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('property_tags',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('slug', sa.String(length=50), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('tag_category', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('sources',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('slug', sa.String(length=50), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('base_url', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('tier', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('external_id')
    )
    op.create_table('properties',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('canonical_hash', sa.String(length=64), nullable=False),
    sa.Column('address_line1', sa.String(length=255), nullable=False),
    sa.Column('address_city', sa.String(length=100), nullable=False),
    sa.Column('address_state', sa.String(length=2), nullable=False),
    sa.Column('address_zip', sa.String(length=10), nullable=True),
    sa.Column('geography_id', sa.Integer(), nullable=True),
    sa.Column('beds', sa.Numeric(precision=4, scale=1), nullable=True),
    sa.Column('baths', sa.Numeric(precision=4, scale=1), nullable=True),
    sa.Column('sqft', sa.Integer(), nullable=True),
    sa.Column('lot_area_value', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('lot_area_unit', sa.String(length=20), nullable=True),
    sa.Column('year_built', sa.SmallInteger(), nullable=True),
    sa.Column('property_type', sa.String(length=50), nullable=True),
    sa.Column('zillow_zpid', sa.String(length=50), nullable=True),
    sa.Column('parcel_apn', sa.String(length=100), nullable=True),
    sa.Column('latitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['geography_id'], ['geographies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('canonical_hash')
    )
    op.create_index('ix_properties_geography', 'properties', ['geography_id'], unique=False)
    op.create_index('ix_properties_state_city', 'properties', ['address_state', 'address_city'], unique=False)
    op.create_index('ix_properties_zip', 'properties', ['address_zip'], unique=False)
    op.create_index('ix_properties_zpid', 'properties', ['zillow_zpid'], unique=False)
    op.create_table('scrape_runs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('run_uuid', sa.String(length=36), nullable=False),
    sa.Column('geography_id', sa.Integer(), nullable=False),
    sa.Column('lead_type_id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('trigger_type', sa.String(length=20), nullable=False),
    sa.Column('triggered_by', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('pages_fetched', sa.Integer(), nullable=False),
    sa.Column('raw_count', sa.Integer(), nullable=False),
    sa.Column('new_count', sa.Integer(), nullable=False),
    sa.Column('updated_count', sa.Integer(), nullable=False),
    sa.Column('duplicate_count', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('run_month', sa.String(length=7), nullable=False),
    sa.Column('zillow_url', sa.Text(), nullable=True),
    sa.Column('raw_blob_path', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['geography_id'], ['geographies.id'], ),
    sa.ForeignKeyConstraint(['lead_type_id'], ['lead_types.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('run_uuid')
    )
    op.create_index('ix_scrape_runs_geo_lt', 'scrape_runs', ['geography_id', 'lead_type_id'], unique=False)
    op.create_index('ix_scrape_runs_month', 'scrape_runs', ['run_month'], unique=False)
    op.create_index('ix_scrape_runs_status', 'scrape_runs', ['status'], unique=False)
    op.create_table('lead_list_definitions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('geography_id', sa.Integer(), nullable=False),
    sa.Column('lead_type_id', sa.Integer(), nullable=False),
    sa.Column('list_month', sa.String(length=7), nullable=False),
    sa.Column('scrape_run_id', sa.BigInteger(), nullable=True),
    sa.Column('property_count', sa.Integer(), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['geography_id'], ['geographies.id'], ),
    sa.ForeignKeyConstraint(['lead_type_id'], ['lead_types.id'], ),
    sa.ForeignKeyConstraint(['scrape_run_id'], ['scrape_runs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('geography_id', 'lead_type_id', 'list_month', name='uq_lead_list')
    )
    op.create_index('ix_lead_lists_geo_lt', 'lead_list_definitions', ['geography_id', 'lead_type_id'], unique=False)
    op.create_index('ix_lead_lists_month', 'lead_list_definitions', ['list_month'], unique=False)
    op.create_table('property_observations',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('property_id', sa.BigInteger(), nullable=False),
    sa.Column('scrape_run_id', sa.BigInteger(), nullable=False),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('price_per_sqft', sa.Numeric(precision=8, scale=2), nullable=True),
    sa.Column('listing_status', sa.String(length=50), nullable=True),
    sa.Column('days_on_market', sa.Integer(), nullable=True),
    sa.Column('zillow_url', sa.String(length=1000), nullable=True),
    sa.Column('raw_json', sa.Text(), nullable=True),
    sa.Column('observed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('run_month', sa.String(length=7), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.ForeignKeyConstraint(['scrape_run_id'], ['scrape_runs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('property_id', 'scrape_run_id', name='uq_observation')
    )
    op.create_index('ix_observations_month', 'property_observations', ['run_month'], unique=False)
    op.create_index('ix_observations_property', 'property_observations', ['property_id'], unique=False)
    op.create_index('ix_observations_run', 'property_observations', ['scrape_run_id'], unique=False)
    op.create_table('property_tag_map',
    sa.Column('property_id', sa.BigInteger(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.Column('tagged_by', sa.String(length=50), nullable=False),
    sa.Column('tagged_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['property_tags.id'], ),
    sa.PrimaryKeyConstraint('property_id', 'tag_id')
    )
    op.create_index('ix_tag_map_tag', 'property_tag_map', ['tag_id'], unique=False)
    op.create_table('lead_list_membership',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('lead_list_id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.BigInteger(), nullable=False),
    sa.Column('observation_id', sa.BigInteger(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.Column('added_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['lead_list_id'], ['lead_list_definitions.id'], ),
    sa.ForeignKeyConstraint(['observation_id'], ['property_observations.id'], ),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lead_list_id', 'property_id', name='uq_list_membership')
    )
    op.create_index('ix_membership_list', 'lead_list_membership', ['lead_list_id'], unique=False)
    op.create_index('ix_membership_property', 'lead_list_membership', ['property_id'], unique=False)
    op.create_table('user_lead_requests',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('geography_id', sa.Integer(), nullable=False),
    sa.Column('lead_type_id', sa.Integer(), nullable=False),
    sa.Column('requested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('served_from', sa.String(length=20), nullable=True),
    sa.Column('lead_list_id', sa.Integer(), nullable=True),
    sa.Column('properties_served', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['geography_id'], ['geographies.id'], ),
    sa.ForeignKeyConstraint(['lead_list_id'], ['lead_list_definitions.id'], ),
    sa.ForeignKeyConstraint(['lead_type_id'], ['lead_types.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_property_map',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.BigInteger(), nullable=False),
    sa.Column('pipeline_stage_id', sa.Integer(), nullable=True),
    sa.Column('saved_from_list_id', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_favorite', sa.Boolean(), nullable=False),
    sa.Column('skip_trace_status', sa.String(length=20), nullable=False),
    sa.Column('comp_status', sa.String(length=20), nullable=False),
    sa.Column('saved_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['pipeline_stage_id'], ['pipeline_stages.id'], ),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.ForeignKeyConstraint(['saved_from_list_id'], ['lead_list_definitions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'property_id', name='uq_user_property')
    )
    op.create_index('ix_upm_property', 'user_property_map', ['property_id'], unique=False)
    op.create_index('ix_upm_stage', 'user_property_map', ['pipeline_stage_id'], unique=False)
    op.create_index('ix_upm_user', 'user_property_map', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_upm_user', table_name='user_property_map')
    op.drop_index('ix_upm_stage', table_name='user_property_map')
    op.drop_index('ix_upm_property', table_name='user_property_map')
    op.drop_table('user_property_map')
    op.drop_table('user_lead_requests')
    op.drop_index('ix_membership_property', table_name='lead_list_membership')
    op.drop_index('ix_membership_list', table_name='lead_list_membership')
    op.drop_table('lead_list_membership')
    op.drop_index('ix_tag_map_tag', table_name='property_tag_map')
    op.drop_table('property_tag_map')
    op.drop_index('ix_observations_run', table_name='property_observations')
    op.drop_index('ix_observations_property', table_name='property_observations')
    op.drop_index('ix_observations_month', table_name='property_observations')
    op.drop_table('property_observations')
    op.drop_index('ix_lead_lists_month', table_name='lead_list_definitions')
    op.drop_index('ix_lead_lists_geo_lt', table_name='lead_list_definitions')
    op.drop_table('lead_list_definitions')
    op.drop_index('ix_scrape_runs_status', table_name='scrape_runs')
    op.drop_index('ix_scrape_runs_month', table_name='scrape_runs')
    op.drop_index('ix_scrape_runs_geo_lt', table_name='scrape_runs')
    op.drop_table('scrape_runs')
    op.drop_index('ix_properties_zpid', table_name='properties')
    op.drop_index('ix_properties_zip', table_name='properties')
    op.drop_index('ix_properties_state_city', table_name='properties')
    op.drop_index('ix_properties_geography', table_name='properties')
    op.drop_table('properties')
    op.drop_table('users')
    op.drop_table('sources')
    op.drop_table('property_tags')
    op.drop_table('pipeline_stages')
    op.drop_table('lead_types')
    op.drop_table('geographies')
    # ### end Alembic commands ###
